const korToEng = {
  레드: "red",
  옐로우: "yellow",
  그린: "green",
  블루: "blue",
  네이비: "navy",
  베이지: "beige",
  연청: "light",
  진청: "dark",
  블랙진: "black",
  크림진: "cream",
  카키: "khaki",
  상의: true,
  하의: false,
  "봄/가을": "autumn",
  여름: "summer",
  겨울: "winter",
  서울: "seoul",
  인천: "incheon",
  경기: "gyeonggi-do",
  대전: "daejeon",
  대구: "daegu",
  부산: "busan",
  울산: "ulsan",
  제주: "jeju",
  "-": "-",
};

export default korToEng;
