name: logic server build and deploy

on:
  push:
    tags:
      - 'v*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fmowl10/clist-logic

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Logic
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zipping built files
        run: zip -r ${{ github.sha }}.zip src requirements.txt Dockerfile

      - name: Upload built artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-artifact
          path: Logic/${{ github.sha }}.zip

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v3
        with:
          name: built-artifact

      - name: Unzipping built files
        run: |
          unzip ${{ github.sha }}.zip
          rm ${{ github.sha }}.zip

      - name: Login to github registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract meta data
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Build and publish container image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
